services:
  - type: static
    name: e-learning-frontend
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: Frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false
